"""Pydantic data models for the 4-layer memory system."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class MemoryLink(BaseModel):
    """A link between two memory notes."""

    target_id: str
    relationship: str = "related_to"  # related_to, supersedes, contradicts, extends


class MemoryNote(BaseModel):
    """Atomic memory note inspired by A-Mem's Zettelkasten approach.

    Used for Semantic Memory (facts about project/user/patterns)
    and Procedural Memory (reusable coding skills).
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    layer: Literal["semantic", "episodic", "procedural"]
    content: str
    keywords: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    context: str = ""  # Rich context description generated by LLM
    embedding: list[float] = Field(default_factory=list)
    links: list[MemoryLink] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    access_count: int = 0


class EpisodicFact(BaseModel):
    """A structured fact extracted from an episode."""

    subject: str
    predicate: str
    object: str


class EpisodicRecord(BaseModel):
    """Timestamped interaction event inspired by REMem.

    Stores what happened in a coding session with rich metadata
    for temporal queries and graph-based retrieval.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    timestamp: datetime = Field(default_factory=datetime.now)
    gist: str  # One-line summary of what happened
    facts: list[EpisodicFact] = Field(default_factory=list)
    files_involved: list[str] = Field(default_factory=list)
    action_type: Literal["refactor", "debug", "feature", "test", "explain", "other"] = "other"
    outcome: Literal["success", "failure", "partial", "unknown"] = "unknown"
    embedding: list[float] = Field(default_factory=list)


class MemorySkill(BaseModel):
    """Reusable coding skill inspired by MemSkill.

    Each skill is a structured template for handling a specific
    type of coding task.
    """

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str  # e.g. "debug_import_error"
    purpose: str  # What this skill does
    when_to_use: str  # Trigger conditions
    how_to_apply: str  # Step-by-step instructions
    constraints: str = ""  # Limitations
    success_rate: float = 0.0
    usage_count: int = 0
    created_from: Literal["manual", "auto_evolved"] = "manual"
    embedding: list[float] = Field(default_factory=list)


class WorkingMemory(BaseModel):
    """Always-in-context memory, compressed when needed.

    Inspired by MEM1's 'memory is reasoning' and LightMem's
    topic-aware short-term memory.
    """

    task_summary: str = ""
    active_files: list[str] = Field(default_factory=list)
    recent_outputs: list[str] = Field(default_factory=list)  # Last N tool outputs
    user_preferences: dict = Field(default_factory=dict)
    internal_state: str = ""  # Compressed historical context

    def compress(self) -> str:
        """Generate a compressed representation for context injection."""
        parts = []
        if self.task_summary:
            parts.append(f"Current task: {self.task_summary}")
        if self.active_files:
            parts.append(f"Active files: {', '.join(self.active_files)}")
        if self.internal_state:
            parts.append(f"Context: {self.internal_state}")
        if self.user_preferences:
            prefs = ", ".join(f"{k}={v}" for k, v in self.user_preferences.items())
            parts.append(f"Preferences: {prefs}")
        return "\n".join(parts)


class Session(BaseModel):
    """A conversation session with metadata."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_path: str = ""
    started_at: datetime = Field(default_factory=datetime.now)
    last_active: datetime = Field(default_factory=datetime.now)
    turn_count: int = 0
    summary: str = ""


class FactOperation(BaseModel):
    """A memory operation decided by the LLM (Mem0-style)."""

    operation: Literal["ADD", "UPDATE", "DELETE", "NOOP"]
    content: str = ""
    target_id: str = ""  # For UPDATE/DELETE
    keywords: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
